# Generated by Django 5.1.1 on 2024-09-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actorName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CensorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20, null=True)),
                ('certifedBy', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectorName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MovieDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Title', models.CharField(max_length=30)),
                ('ReleasedYear', models.IntegerField(null=True)),
                ('Description', models.TextField()),
                ('MoviePic', models.ImageField(null=True, upload_to='poster')),
                ('cast', models.ManyToManyField(related_name='moviecast', to='myapp.actor')),
                ('censoredBy', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='myapp.censorinfo')),
                ('movieDirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directedBy', to='myapp.director')),
            ],
        ),
    ]
